import { useState } from "react";
import { ArrowRight, Check, ChevronDown, Play, Users, TrendingUp, ShieldCheck, Compass } from "lucide-react";
import "./ignite.css";

const MEDIA = "https://storage.googleapis.com/msgsndr/ZsBUSW0nlx5d5Mjpk3ph/media/";
const BOOKING = "https://calendly.com/colinsprake/call-with-colin-ceo-local-handyman";
const PRESENTATION = "https://gamma.app/docs/Where-Business-Owners-Are-Built-uue52js25itoxlc";
const series = [
  { title: "How do I hire handymen?", topic: "Build your team", id: "685562ceac9458c952ae02aa", poster: "68556812ca34e3c5bb2a011c.png", description: "See how our recruitment systems help you find and hire the people who will deliver your service." },
  { title: "How do I get customers?", topic: "Win local business", id: "685562ceac9458ea29ae02a9", poster: "685568121a74cd66b86a23a2.png", description: "Explore the three pillars of bringing business into your Local Handyman territory." },
  { title: "How do I grow and scale?", topic: "Build beyond the first van", id: "685562ce9f0e4c819816f2d7", poster: "685568121a74cd082e6a23a1.png", description: "Understand how the model supports growth as you develop your team and local operation." },
  { title: "What systems and support do I get?", topic: "Have a team behind you", id: "685562ce8b29500e346e5cff", poster: "6855690bb596227f95de4a62.png", description: "Get a closer look at the tools, training, and ongoing support available to Success Partners." },
];
const stages = [
  { title: "Introductory call", label: "Qualification & your goals", description: "Let's get to know each other. Review Ignite and the Success Partner presentation, talk through your goals, dreams, and desires, and discuss funding requirements.", next: "Next: book your discovery call", tasks: ["Your goals and ownership fit", "Business overview and funding requirements"] },
  { title: "Discovery call", label: "Explore the opportunity", description: "Walk through the brand in detail, discuss the Vivid Vision and Franchise Disclosure Document (FDD), and explore territories and availability.", next: "Next: book your CEO fit call", tasks: ["Full brand and territory review", "Vision and disclosure discussion"] },
  { title: "CEO fit call & due diligence", label: "Make an informed decision", description: "Confirm cultural alignment and mutual fit. If you choose to move forward, access the Success Portal and complete your due diligence, including legal review, entity setup, and validation calls with Success Partners.", next: "Next: complete your review and confirm fit", tasks: ["Meet the CEO and ask your questions", "FDD legal review and partner validation calls"] },
  { title: "Welcome to the family", label: "Prepare for launch", description: "Connect with funding partners, confirm your territory and any applicable first-refusal rights, arrange five-day training, complete the agreement instructions, and finalize signing and payment before onboarding.", next: "Next: training, onboarding, and your launch", tasks: ["Territory, funding, and agreement completion", "Five-day training and launch preparation"] },
];
const faqs = [
  ["Do I need trades experience?", "No trades background is required. Your role is to lead the business and build a team of skilled technicians. We support you with training, recruitment tools, and operating systems."],
  ["What investment and funding will I need?", "Colin will walk you through current franchise fees, startup costs, working capital, and funding options for your circumstances. Review the current disclosure documents and confirm the full investment before making a decision."],
  ["What training and ongoing support are included?", "The 60-day Momentum program covers cash flow, sales, marketing, and operations. Ongoing training and collaboration calls help you keep learning alongside other Success Partners."],
  ["How does marketing support work?", "Local Handyman supports your website, design, SEO, copywriting, and content, along with print, offline, social, and online marketing tools. You also build relationships and local visibility in your community."],
  ["Can I speak with existing Success Partners?", "Yes. Validation calls are part of the discovery and due diligence process. We can introduce you to current owners so you can ask about their experience directly."],
  ["How do territories and timing work?", "Available territories, exclusivity, and any adjacent-territory rights are discussed during discovery and confirmed in your agreement. Your timeline depends on due diligence, funding, training, and launch readiness; Colin will walk through it with you."],
];

function track(event: string, detail: string) {
  (window as Window & { dataLayer?: Record<string, unknown>[] }).dataLayer?.push({ event, page: "ignite", detail });
}
function Booking({ location, children = "Book a call with Colin" }: { location: string; children?: React.ReactNode }) {
  return <a className="ig-button" href={BOOKING} target="_blank" rel="noopener noreferrer" onClick={() => track("ignite_booking_click", location)}>{children}<ArrowRight size={18} aria-hidden="true" /></a>;
}
function Video({ id, title, poster }: { id: string; title: string; poster?: string }) {
  const [failed, setFailed] = useState(false);
  return <div className="ig-video-wrap">
    <video controls playsInline preload="metadata" tabIndex={0} aria-label={title} poster={poster ? `${MEDIA}${poster}` : undefined} onPlay={() => track("ignite_video_play", title)} onEnded={() => track("ignite_video_complete", title)} onError={() => setFailed(true)}>
      <source src={`${MEDIA}${id}.mp4#t=0.5`} type="video/mp4" />
      Your browser does not support embedded video.
    </video>
    {failed && <p className="ig-video-error" role="status">Having trouble playing this video? <a href={`${MEDIA}${id}.mp4`} target="_blank" rel="noopener noreferrer">Open {title}</a>.</p>}
  </div>;
}
function Heading({ eyebrow, title, children }: { eyebrow: string; title: string; children?: React.ReactNode }) {
  return <div className="ig-section-heading"><p className="ig-eyebrow">{eyebrow}</p><h2>{title}</h2>{children && <p className="ig-intro">{children}</p>}</div>;
}

export default function Ignite() {
  return <div className="ignite">
    <a href="#ignite-main" className="ig-skip">Skip to content</a>
    <header className="ig-header"><div className="ig-container ig-header-inner">
      <a href="#ignite-main" aria-label="Local Handyman Ignite, top of page"><img src="/images/handymanlogo_d9f89eaa.png" alt="Local Handyman" width="135" height="67" /></a>
      <nav aria-label="Ignite page"><a href="#the-series">4-part video series</a><a href="#your-journey">Your journey</a><a href="#questions">Questions</a></nav>
      <Booking location="header" />
    </div></header>
    <main id="ignite-main">
      <section className="ig-hero"><div className="ig-container ig-hero-grid">
        <div><p className="ig-eyebrow">LOCAL HANDYMAN / IGNITE</p><h1>Don’t pick up<br />the hammer.<br /><span>Run the business.</span></h1><p className="ig-hero-copy">Build your future with the people, systems, and support to help you lead a Local Handyman business.</p><Booking location="hero" /><a className="ig-text-link ig-hero-secondary" href="#the-series"><Play size={15} aria-hidden="true" /> Start with the four key questions</a><div className="ig-hero-note"><span /> Your first step toward becoming a Success Partner.</div></div>
        <figure className="ig-hero-film"><Video id="677aeb68b0a11f29d6c5eb3d" poster="675ff435fb63bc30765fb086.png" title="A welcome from Colin Sprake" /><figcaption><span className="ig-film-label">START HERE</span><strong>A welcome from Colin Sprake</strong><span>Local Handyman Owner & CEO</span></figcaption></figure>
      </div></section>
      <div className="ig-strip"><div className="ig-container"><span><Check size={18} aria-hidden="true" /> No trades experience needed</span><span><Check size={18} aria-hidden="true" /> Systems for business owners</span><span><Check size={18} aria-hidden="true" /> Support beyond your launch</span></div></div>
      <section className="ig-section"><div className="ig-container">
        <Heading eyebrow="THE OPPORTUNITY" title="A local need. A business you can lead.">Homeowners need dependable help. Local Handyman brings a recognizable brand, operating systems, and a support network to an essential local service.</Heading>
        <div className="ig-three"><article className="ig-value"><Users aria-hidden="true" /><h3>You bring the leadership</h3><p>Build relationships, hire your team, and lead the operation. Skilled technicians deliver the work.</p></article><article className="ig-value"><TrendingUp aria-hidden="true" /><h3>A model built for growth</h3><p>Develop your local presence and grow your operation as your customer base and team expand.</p></article><article className="ig-value"><ShieldCheck aria-hidden="true" /><h3>You have support</h3><p>Access business training, marketing resources, and an experienced network of fellow Success Partners.</p></article></div>
      </div></section>
      <section id="partners" className="ig-section ig-soft"><div className="ig-container"><Heading eyebrow="HEAR IT FROM THE OWNERS" title="Real people. Their own stories.">Meet a few of the Success Partners building Local Handyman businesses in their communities.</Heading>
        <div className="ig-two ig-partners">{[
          ["Regina, SK", "67fcd4be71384bfbb2b4a6d3"], ["Kelowna, BC", "67fcd76071384b162bb4b8e1"], ["Lethbridge, AB", "67fce03fc7a015f2f6d833a6"], ["Calgary, AB", "67fcdcee56be24f746e4ad2b"],
        ].map(([city, id]) => <figure className="ig-partner" key={id}><Video id={id} title={`${city} Success Partner story`} /><figcaption><strong>{city}</strong><span>Local Handyman Success Partners</span></figcaption></figure>)}</div>
      </div></section>
      <section className="ig-section"><div className="ig-container ig-two ig-align-center"><img className="ig-team-photo" src="/images/atlanta_team_3_38aba96a.jpg" alt="Local Handyman team beside their branded van" loading="lazy" /><div><Heading eyebrow="WHAT MAKES US DIFFERENT" title="Build a business with a team behind you." /><p className="ig-intro">You bring ambition and a commitment to your community. We bring tools and support to help turn that commitment into a well-run business.</p><ul className="ig-check-list"><li><Check aria-hidden="true" /> Recruitment systems to help build your team</li><li><Check aria-hidden="true" /> Marketing resources to build local visibility</li><li><Check aria-hidden="true" /> Training across sales, cash flow, and operations</li><li><Check aria-hidden="true" /> Collaboration with other Success Partners</li></ul><Booking location="difference">Ask Colin your questions</Booking></div></div></section>
      <section className="ig-section ig-navy"><div className="ig-container"><div className="ig-two ig-align-center"><div><Heading eyebrow="MEET THE PEOPLE BEHIND THE BRAND" title="Your success matters to us." /><h3 className="ig-colin">Colin Sprake</h3><p className="ig-role">Local Handyman Owner & CEO</p><p className="ig-intro">Get to know Colin and the approach behind Local Handyman. His focus is helping Success Partners become confident business owners through mentorship, practical systems, and ongoing support.</p><Booking location="colin" /></div><figure><Video id="68416b043eb51980ce366389" poster="67603c6888b4df022d30c950.png" title="Get to know Colin and Local Handyman" /><figcaption className="ig-caption">A closer look at the leadership behind Local Handyman.</figcaption></figure></div><div className="ig-support-row"><div><Compass aria-hidden="true" /><h3>Business guidance</h3><p>Training and support as you build your operation.</p></div><div><Users aria-hidden="true" /><h3>Partner community</h3><p>Connect, collaborate, and learn from other owners.</p></div><div><TrendingUp aria-hidden="true" /><h3>Marketing support</h3><p>Brand, tools, and resources for local visibility.</p></div></div></div></section>
      <section className="ig-section"><div className="ig-container"><Heading eyebrow="YOUR PATH TO PARTNERSHIP" title="Get the bigger picture.">Explore the Success Partner presentation for a fuller introduction to the business, the support, and the ownership opportunity.</Heading><div className="ig-presentation"><Video id="67f58138cafd9fe4c9fb91f7" poster="675ff891fb63bca2195fb400.png" title="Colin Sprake Success Partner presentation" /><div className="ig-presentation-footer"><div><strong>The Success Partner presentation</strong><p>Watch here, or explore the accompanying presentation.</p></div><a className="ig-outline" href={PRESENTATION} target="_blank" rel="noopener noreferrer" onClick={() => track("ignite_presentation_click", "presentation")}>Open presentation <ArrowRight size={17} aria-hidden="true" /></a></div></div></div></section>
      <section id="the-series" className="ig-section ig-soft"><div className="ig-container"><Heading eyebrow="THE FOUR-PART VIDEO SERIES" title="Four questions. Straight answers.">Watch these short videos before your call with Colin. They cover the questions we hear most often, so you can spend your conversation on what matters to you.</Heading><div className="ig-two">{series.map((video, index) => <article className="ig-series-card" key={video.id}><Video id={video.id} title={video.title} poster={video.poster} /><div className="ig-series-body"><p className="ig-eyebrow">PART {String(index + 1).padStart(2, "0")} / {video.topic}</p><h3>{video.title}</h3><p>{video.description}</p></div></article>)}</div><div className="ig-series-cta"><p>Got your questions ready? Let’s talk them through.</p><Booking location="series" /></div></div></section>
      <section id="your-journey" className="ig-section"><div className="ig-container"><Heading eyebrow="YOUR JOURNEY TO BECOMING A SUCCESS PARTNER" title="Know what comes next.">From your first conversation to launch preparation, here’s the flow of calls and decisions. Colin will guide you through the next step for your situation.</Heading><ol className="ig-timeline">{stages.map((stage, index) => <li key={stage.title}><span className="ig-step-number" aria-hidden="true">0{index + 1}</span><div className="ig-step-body"><p className="ig-eyebrow">{stage.label}</p><h3>{stage.title}</h3><p>{stage.description}</p><ul>{stage.tasks.map(task => <li key={task}><Check size={16} aria-hidden="true" />{task}</li>)}</ul><p className="ig-step-next"><ArrowRight size={17} aria-hidden="true" />{stage.next}</p></div></li>)}</ol><p className="ig-timing">The original journey outlines approximately 4–8 weeks for the discovery and decision process, followed by launch preparation. Actual timing depends on your circumstances and completion of each step.</p></div></section>
      <section className="ig-section ig-fit"><div className="ig-container"><Heading eyebrow="IS LOCAL HANDYMAN RIGHT FOR YOU?" title="Bring the ambition. Build with intention.">This is an active business ownership opportunity for people ready to invest their time, energy, and leadership.</Heading><div className="ig-three">{[["Growth-oriented", "You want to build a team and develop a business in your community."], ["Decisive and driven", "You ask good questions, make informed decisions, and take action."], ["Ready to lead", "You’re willing to follow systems, build relationships, and commit to the work."]].map(([title, text]) => <article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
      <section id="questions" className="ig-section"><div className="ig-container ig-faq"><Heading eyebrow="YOUR QUESTIONS, ANSWERED" title="Let’s clear a few things up." />{faqs.map(([question, answer]) => <details key={question}><summary>{question}<ChevronDown size={20} aria-hidden="true" /></summary><p>{answer}</p></details>)}</div></section>
      <section className="ig-final"><div className="ig-container"><p className="ig-eyebrow">YOUR NEXT CHAPTER STARTS WITH A CONVERSATION</p><h2>Let’s see what we<br />can build together.</h2><p>Bring your questions. Talk directly with Colin.<br />Find out whether Local Handyman is the right fit for you.</p><Booking location="final" /><a className="ig-back" href="#the-series">Watch the four-part series first ↑</a></div></section>
    </main>
    <footer className="ig-footer"><div className="ig-container"><div className="ig-footer-top"><img src="/images/handymanlogo_d9f89eaa.png" alt="Local Handyman" width="120" height="60" /><p>Local business. Shared ambition.</p><a href="https://www.localhandymangroup.com/privacy" target="_blank" rel="noopener noreferrer">Privacy policy</a></div><p>This information is for informational purposes only and is not an offer to sell or a solicitation of an offer to buy a franchise. An offer can only be made through the applicable franchise disclosure documents and in compliance with applicable registration and disclosure requirements. Individual experiences and results vary.</p><p>FOR THE STATE OF NEW YORK: This advertisement is not an offering. An offering can be made only by a prospectus filed first with the Department of Law of the State of New York. Such filing does not constitute approval by the Department of Law.</p><p>© {new Date().getFullYear()} Local Handyman Group. All rights reserved.</p></div></footer>
  </div>;
}
